### ISSUE TITLE
Gun game "points to win" can be broken, edit menu.rs to fix

### ISSUE THREAD

**Issue by NoviceAbeca** [deffen3/rally_game#12]
May want to make the points to win be a count based on the number of weapons you have set to be included in the gun game.

**Comment by deffen3** [comment]
I'm going to fix this simply by having the last gun-game weapon wrap around to the first weapon. So if you really want to play gun-game style up to a really high score, then any "points to win" will now be valid.

Eventually the gun-game weapon list will be added into the weapon config menus anyway, so more information about how this works can be provided there.
