### ISSUE TITLE
Release/Debug build incompatibility - crashing because game can't find .ron files

### ISSUE THREAD

**Issue by deffen3** [deffen3/rally_game#23]
src/components/vehicles.rs: build_vehicle_store()
src/components/arena.rs: build_arena_store()
src/components/weapons.rs: build_weapon_store()

Initially I was following the amethyst pong tutorial to specify my .ron filenames, which used env!("CARGO_MANIFEST_DIR"). This works fine for cargo debug builds. 

When I went try to do a cargo release build the game was crashing because it couldn't find the .ron files.

So I looked into this issue online and found that there was the amethyst::utils::application_root_dir function. But this doesn't seem super great, because it is either env!("CARGO_MANIFEST_DIR") for debug builds, or std::env::current_exe() for release builds. I think what I really want is std::env::current_dir.

However I must have been doing something wrong, because I was getting crazy path like this:

/* Release rally.exe (crashes):
"\\\\?\\C:\\Users\\Mike\\rust\\amethyst\\rally_game\\target\\release\\assets/game/vehicles.ron"

cargo run
"C:\\Users\\Mike\\rust\\amethyst\\rally_game\\assets/game/vehicles.ron"
*/

pub fn build_vehicle_store(world: &mut World) -> VehicleStoreResource {
    // let app_root = current_dir();
    // let input_path = app_root.unwrap().join("assets/game/vehicles.ron");

    let input_path_properties = format!("{}/assets/game/vehicle_properties.ron", env!("CARGO_MANIFEST_DIR"));
...

I need to take another look at it though as it's been awhile since I looked at this.

**Comment by paulkernfeld** [comment]
Zooming unnecessarily out to think about app packaging in general, there are a few different dimensions of configuration to think about:

- Is the configuration hardware-specific? E.g. one user may have a 4K monitor where another has Xbox controllers. You probably would want this configuration to persist even if you installed a new version of the game, assuming it would be compatible.
- Is the configuration a "collection?" For example, weapons or maps. A user might want to create their own weapons or maps, or to modify the built-in weapons or maps.
- Will users want to contribute configuration upstream? Could be a user-created map or a user's tweak to improve a built-in map.

Eventually [`app_dirs_2`](https://github.com/app-dirs-rs/app_dirs2) or [`directories`](https://crates.io/crates/directories) might be interesting.

**Comment by paulkernfeld** [comment]
I think that basing the release build off `std::env::current_exe()` might be smart because it would be cool for the app to always work no matter what directory it's run from.

Take a look at the PR I made; it works on MacOS with both `cargo run --debug` and `cargo run --release`.

**Comment by deffen3** [comment]
Hmm, I like the solution so far but I'm still having an issue when I try to execute the release .exe.

I'm going to merge the pull request because it's still an improvement to the code.

So I too can run the game using both cargo run --debug and cargo run --release. But I can't run either debug or release rally.exe by clicking on the .exe file. I have a copy of the entire assets folder in C:\Users\Mike\rust\amethyst\rally_game\target\release.


```
PS C:\Users\Mike\rust\amethyst\rally_game\target\release> .\rally.exe
Error: Error { inner: Inner { source: None, backtrace: Some(   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: amethyst_error::new_backtrace
   3: <amethyst_error::Error as core::convert::From<T>>::from
   4: rally::load_ron_asset
   5: <T as core::any::Any>::type_id
   6: std::rt::lang_start_internal::{{closure}}
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\rt.rs:52
   7: std::panicking::try::do_call<closure-0,i32>
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:305
   8: panic_unwind::__rust_maybe_catch_panic
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libpanic_unwind\lib.rs:86
   9: std::panicking::try
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:281
  10: std::panic::catch_unwind
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panic.rs:394
  11: std::rt::lang_start_internal
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\rt.rs:51
  12: main
  13: invoke_main
             at d:\A01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  14: __scrt_common_main_seh
             at d:\A01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  15: BaseThreadInitThunk
  16: RtlUserThreadStart
), error: ConfigError(File(Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." })) } }
```

**Comment by paulkernfeld** [comment]
Ah, okay, that makes sense. Can you post the stack trace that you get when you run the debug EXE (not from cargo)? Because it's built in debug mode, that backtrace should have line numbers, which will make it easier to see exactly what file it's trying to fine.

**Comment by paulkernfeld** [comment]
Never mind, I realize I can do that on my machine. I get this:

```
Error: Error { inner: Inner { source: None, backtrace: Some(   0: backtrace::backtrace::libunwind::trace
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
      backtrace::backtrace::trace_unsynchronized
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   1: backtrace::backtrace::trace
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:53
   2: backtrace::capture::Backtrace::create
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/capture.rs:164
   3: backtrace::capture::Backtrace::new
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/capture.rs:128
   4: amethyst_error::new_backtrace
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst_error-0.5.0/src/lib.rs:342
   5: amethyst_error::Error::new
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst_error-0.5.0/src/lib.rs:57
   6: <amethyst_error::Error as core::convert::From<T>>::from
             at /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst_error-0.5.0/src/lib.rs:172
   7: rally::main
             at src/main.rs:68
   8: std::rt::lang_start::{{closure}}
             at /Users/paul/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/rt.rs:67
   9: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
      std::panicking::try::do_call
             at src/libstd/panicking.rs:331
      std::panicking::try
             at src/libstd/panicking.rs:274
      std::panic::catch_unwind
             at src/libstd/panic.rs:394
      std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  10: std::rt::lang_start
             at /Users/paul/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/rt.rs:67
  11: main
), error: ConfigError(File(Os { code: 2, kind: NotFound, message: "No such file or directory" })) } }
```

**Comment by paulkernfeld** [comment]
Oh, it looks like, in addition to the `assets` folder you also need a copy of the `config` folder within `target/release`. Does that solve the issue?

**Comment by deffen3** [comment]
Ah yes, silly me. That was exactly the issue. Awesome!
